# Generated by Django 2.1.7 on 2019-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('student_dpt', models.CharField(max_length=100)),
                ('student_img', models.ImageField(upload_to='Pictures')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
