# Generated by Django 2.1.7 on 2019-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191005_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
