# Generated by Django 2.1.7 on 2019-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191005_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
